#!/bin/sh
# Shared helpers. Source from scripts, do not execute:
#   . "$script_dir/../../common/lib.sh"
# Deliberately init-system agnostic: no service helpers here.

log() {
    printf '>>> %s\n' "$*"
}

die() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

require_root() {
    [ "$(id -u)" -eq 0 ] || die "must run as root"
}

# Print the first known package manager found in PATH.
detect_pm() {
    for _pm in pacman apt emerge; do
        if command -v "$_pm" >/dev/null 2>&1; then
            printf '%s\n' "$_pm"
            return 0
        fi
    done
    return 1
}

# Bind sshd to the tailnet only. Writes the nonlocal_bind sysctl (so sshd
# can bind a tailscale IP that does not exist yet at boot -- no service
# ordering to race), then generates the ListenAddress drop-in from whatever
# IPs tailscale holds right now. Config files only, per the no-service-
# helpers rule above: enabling/starting sshd is the caller's job, and ONLY
# when this returns 0. On a machine without a tailscale IP (chroot, logged
# out) it returns 1 -- enabling sshd anyway would expose port 22 on every
# interface, which is the one thing this setup exists to prevent.
install_sshd_tailnet() {
    cat > /etc/sysctl.d/91-ssh-tailnet.conf <<'EOF'
# sshd binds the tailscale IPs (/etc/ssh/sshd_config.d/10-tailnet.conf),
# which do not exist until tailscaled is up. nonlocal_bind lets the bind
# succeed whoever wins that boot race; packets simply start arriving once
# tailscale0 appears.
net.ipv4.ip_nonlocal_bind = 1
net.ipv6.ip_nonlocal_bind = 1
EOF
    log "wrote /etc/sysctl.d/91-ssh-tailnet.conf"

    _ts4=$(tailscale ip -4 2>/dev/null) || _ts4=''
    _ts6=$(tailscale ip -6 2>/dev/null) || _ts6=''
    if [ -z "$_ts4" ]; then
        log "tailscale has no IP (chroot? logged out?): leaving sshd alone, rerun after tailscale up"
        return 1
    fi
    mkdir -p /etc/ssh/sshd_config.d
    {
        echo '# Generated by deployLinux (install_sshd_tailnet in common/lib.sh):'
        echo '# sshd is reachable over the tailnet only, LAN/WAN never see it.'
        echo "ListenAddress $_ts4"
        if [ -n "$_ts6" ]; then
            echo "ListenAddress $_ts6"
        fi
        echo 'PermitRootLogin no'
    } > /etc/ssh/sshd_config.d/10-tailnet.conf
    # first-obtained wins in sshd_config, so the Include must sit at the
    # top. Both distros ship it there; this guards a config without one.
    if ! grep -Eq '^[[:space:]]*Include[[:space:]].*sshd_config\.d' /etc/ssh/sshd_config; then
        sed -i '1i Include /etc/ssh/sshd_config.d/*.conf' /etc/ssh/sshd_config
        log "sshd_config had no Include, added one at the top"
    fi
    log "wrote /etc/ssh/sshd_config.d/10-tailnet.conf ($_ts4${_ts6:+ $_ts6})"
}

# fetch_verify <url> <dest> <sha256>
# Skips the download when dest already matches the checksum.
fetch_verify() {
    _url=$1
    _dest=$2
    _sum=$3
    if [ -f "$_dest" ] && printf '%s  %s\n' "$_sum" "$_dest" | sha256sum -c - >/dev/null 2>&1; then
        log "$_dest already present and verified"
        return 0
    fi
    curl -fL -o "$_dest" "$_url"
    printf '%s  %s\n' "$_sum" "$_dest" | sha256sum -c - || die "checksum mismatch: $_dest"
}
