"Boot default"  "root=PARTUUID=930cb6af-5985-4512-8d3c-b1bbee3f8205 rw nvidia_drm.modeset=1 nvidia_drm.fbdev=1 amd_iommu=on iommu=pt amd_pstate=active"
"Boot verbose"  "root=PARTUUID=930cb6af-5985-4512-8d3c-b1bbee3f8205 rw nvidia_drm.modeset=1 nvidia_drm.fbdev=1 amd_iommu=on iommu=pt amd_pstate=active debug loglevel=7"
"Boot to shell" "root=PARTUUID=930cb6af-5985-4512-8d3c-b1bbee3f8205 rw init=/bin/bash"
